// 

let contador = 0

// enquanto contador for menor do que 10, repita
while (contador <= 10) {
    console.log("olha a hora do café");
    console.log("venha tomar seu café!");
    console.log("café da manhã,café da tarde!não importa");
    console.log("venha tomar o seu café!!!");

    // Adicionar ++ após o nome de uma variável faz com que seja adicionado 1 ao seu valor


    contador++
    console.log(contador);
}


